title: OpenFreebox Revived
description: Reverse engineering of the Freebox Revolution V6
show_downloads: false

remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme

github:
  is_project_page: false

author: 2022 • OpenFreebox Revived
